import { contactPublic } from "@/data/contact";
import type { LegalDocument } from "@/types/legal";

const company = contactPublic.companyName;
const email = contactPublic.generalEmail;

export const disclaimer: LegalDocument = {
  slug: "disclaimer",
  title: "Disclaimer",
  shortTitle: "Disclaimer",
  description:
    "Important notice that LawGPT provides AI-assisted legal information and workflow automation and is not a law firm.",
  lastUpdated: "2026-08-09",
  lastUpdatedLabel: "9 August 2026",
  intro:
    "This Disclaimer explains the nature of LawGPT’s services and the limits of the information, workflows, documents, research, and optional review features available on the platform. Please read it carefully before relying on any output.",
  seo: {
    title: "Disclaimer | LawGPT",
    description:
      "LawGPT provides AI-assisted legal information and workflow automation. It is not a law firm. Read our disclaimer on AI outputs and Lawyer Review+.",
    keywords: [
      "LawGPT disclaimer",
      "not a law firm",
      "AI legal information disclaimer",
      "Lawyer Review+ disclaimer",
    ],
  },
  sections: [
    {
      id: "nature-of-service",
      title: "Nature of the LawGPT service",
      paragraphs: [
        `${company} operates LawGPT, a technology platform that provides AI-assisted legal information, guided legal workflows, lawyer-grade document generation, legal research tools, secure document storage, Legal Guides, platform search, and optional Lawyer Review+.`,
        "LawGPT is designed to help users organise facts, prepare draft materials, and move toward filing-ready packages. It is a software product, not a substitute for a retained advocate or law firm engagement in every situation.",
      ],
    },
    {
      id: "not-a-law-firm",
      title: "LawGPT is not a law firm",
      paragraphs: [
        "LawGPT is not a law firm, advocate partnership, or legal practice. Using the website, creating an account, starting a workflow, generating documents, browsing Legal Guides, submitting a contact form, or purchasing a subscription does not, by itself, create an advocate–client or attorney–client relationship with LawGPT.",
        "Nothing on the platform should be interpreted as LawGPT appearing, representing, or advocating for you before any court, tribunal, authority, or opposing party.",
      ],
    },
    {
      id: "not-legal-advice",
      title: "AI outputs are not legal advice",
      paragraphs: [
        "Unless a human lawyer reviews your matter under Lawyer Review+ (and only to the extent of that review), information and outputs provided by LawGPT—including AI chat or guidance, workflow recommendations, research summaries, generated documents, checklists, and filing packages—should be treated as general legal information and drafting assistance, not as formal legal advice tailored to your complete circumstances.",
        "Laws, procedures, forums, limitation periods, and local practices vary. Your facts may differ from assumptions used by the AI or workflow. You should obtain independent professional advice when your situation requires it.",
      ],
    },
    {
      id: "lawyer-review-plus",
      title: "Lawyer Review+",
      paragraphs: [
        "Lawyer Review+ is an optional paid service in which a legal professional may review selected materials associated with your matter. Where Lawyer Review+ is selected and completed, the reviewer’s professional input applies only to the scope described for that review.",
        "Lawyer Review+ does not mean that LawGPT itself becomes your law firm. It also does not guarantee a particular legal outcome, court acceptance, settlement result, or filing success. Communications and deliverables under Lawyer Review+ should be evaluated in light of the stated review scope and any limitations communicated at the time of the service.",
      ],
    },
    {
      id: "user-responsibility",
      title: "Your responsibility for review and submission",
      paragraphs: [
        "You remain responsible for:",
      ],
      lists: [
        {
          items: [
            "Checking that facts, names, dates, amounts, and allegations are accurate",
            "Reviewing every draft document and filing package before use or submission",
            "Deciding whether to file, send, sign, or rely on any material generated by LawGPT",
            "Meeting deadlines, paying statutory fees, and following the rules of the relevant forum",
            "Seeking independent counsel where the matter is complex, high-stakes, or contested",
          ],
        },
      ],
      subsections: [
        {
          id: "no-guarantee",
          title: "No outcome guarantee",
          paragraphs: [
            "LawGPT does not guarantee that any notice, complaint, petition, representation, or package will be accepted, successful, enforceable, or complete for your purpose.",
          ],
        },
      ],
    },
    {
      id: "legal-guides",
      title: "Legal Guides and website content",
      paragraphs: [
        "Legal Guides, platform pages, pricing descriptions, FAQs, and other website content are provided for education and product information. They may be simplified for readability and may not cover every exception, amendment, or local variation. They are not a complete statement of the law.",
      ],
    },
    {
      id: "third-parties",
      title: "Third parties and authorities",
      paragraphs: [
        "LawGPT is not affiliated with any court, police department, consumer forum, government portal, or regulator unless we expressly say so. References to authorities, statutes, or procedures are for workflow and informational context.",
      ],
    },
    {
      id: "limitation",
      title: "Relationship to Terms and Privacy Policy",
      paragraphs: [
        "This Disclaimer works together with our [Terms of Service](/terms) and [Privacy Policy](/privacy). If you need formal representation, crisis assistance, or advice on whether to commence proceedings, consult a qualified advocate licensed to practise in the relevant jurisdiction.",
      ],
    },
    {
      id: "contact",
      title: "Contact",
      paragraphs: [
        `If you have questions about this Disclaimer, contact [${email}](mailto:${email}) or use the [Contact](/contact) page.`,
      ],
    },
  ],
};
